name: 'Publish to lumamc.net'

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: List icon files in CI
        run: ls -l client/src/assets/icons/

      - name: Publish website to lumamc.net
        uses: gradle/gradle-build-action@v3
        env:
          PTERO_URL: ${{ secrets.PTERO_URL }}
          PTERO_SERVER: ${{ secrets.PTERO_SERVER }}
          PTERO_TOKEN: ${{ secrets.PTERO_TOKEN }}
        with:
          arguments: yarnInstall build --stacktrace
